from __future__ import annotations

from typing import Any, Protocol


class MerchantAdapter(Protocol):
    def validate_credentials(self) -> bool: ...

    def search_candidates(self, query: str, market: str, language: str) -> list[dict[str, Any]]: ...

    def normalize_candidate(self, raw: dict[str, Any]) -> dict[str, Any]: ...

    def build_affiliate_url(self, candidate: dict[str, Any], tracking: dict[str, Any]) -> str: ...

    def refresh_offer(self, candidate_id: str) -> dict[str, Any]: ...

    def validate_policy(self, candidate: dict[str, Any]) -> dict[str, Any]: ...

    def get_required_disclosures(self) -> list[str]: ...
