export interface NewsDetailLabels {
  author: string;
  breadcrumb: string;
  breaking: string;
  contact: string;
  correction: string;
  correctionBody: string;
  defaultReadingTime: string;
  editorialTeam: string;
  home: string;
  keyPoints: string;
  lastUpdated: string;
  news: string;
  noNext: string;
  noPrevious: string;
  noSources: string;
  prevNext: string;
  published: string;
  save: string;
  sectionLabel: string;
  sourceAndCorrection: string;
  sources: string;
  toc: string;
  updated: string;
}

export function newsDetailLabels(language: string): NewsDetailLabels {
  const labels: Record<string, NewsDetailLabels> = {
    en: {
      author: "Author",
      breadcrumb: "Breadcrumb",
      breaking: "Brief",
      contact: "Contact",
      correction: "Corrections",
      correctionBody: "If this article contains an error, we will review and correct it quickly.",
      defaultReadingTime: "About 5 min read",
      editorialTeam: "Review Guide Editorial Team",
      home: "Home",
      keyPoints: "Key points",
      lastUpdated: "Last updated",
      news: "News",
      noNext: "No next article",
      noPrevious: "No previous article",
      noSources: "Public sources are being prepared.",
      prevNext: "Previous and next articles",
      published: "Published",
      save: "Save",
      sectionLabel: "Section",
      sourceAndCorrection: "Sources and corrections",
      sources: "Sources",
      toc: "Table of contents",
      updated: "Updated"
    },
    es: {
      author: "Autor",
      breadcrumb: "Ruta",
      breaking: "Última hora",
      contact: "Contactar",
      correction: "Correcciones",
      correctionBody: "Si detectamos un error, revisaremos el contenido y lo corregiremos rápidamente.",
      defaultReadingTime: "Unos 5 min de lectura",
      editorialTeam: "Equipo editorial de Review Guide",
      home: "Inicio",
      keyPoints: "Puntos clave",
      lastUpdated: "Última actualización",
      news: "Noticias",
      noNext: "No hay siguiente artículo",
      noPrevious: "No hay artículo anterior",
      noSources: "Las fuentes públicas confirmadas están en preparación.",
      prevNext: "Artículos anterior y siguiente",
      published: "Publicado",
      save: "Guardar",
      sectionLabel: "Sección",
      sourceAndCorrection: "Fuentes y correcciones",
      sources: "Fuentes y referencias",
      toc: "Índice del artículo",
      updated: "Actualizado"
    },
    "pt-br": portugueseNewsLabels("Equipe editorial do Review Guide", "Contato", "Artigos anterior e próximo"),
    pt: portugueseNewsLabels("Equipa editorial do Review Guide", "Contacto", "Artigos anterior e seguinte"),
    fr: {
      author: "Auteur",
      breadcrumb: "Fil d'Ariane",
      breaking: "Alerte",
      contact: "Contact",
      correction: "Corrections",
      correctionBody: "Si une erreur est confirmée, nous vérifierons puis corrigerons rapidement l'article.",
      defaultReadingTime: "Environ 5 min de lecture",
      editorialTeam: "Rédaction Review Guide",
      home: "Accueil",
      keyPoints: "Points clés",
      lastUpdated: "Dernière mise à jour",
      news: "Actualités",
      noNext: "Aucun article suivant",
      noPrevious: "Aucun article précédent",
      noSources: "Les sources publiques vérifiées sont en préparation.",
      prevNext: "Articles précédent et suivant",
      published: "Publié",
      save: "Enregistrer",
      sectionLabel: "Section",
      sourceAndCorrection: "Sources et corrections",
      sources: "Sources et références",
      toc: "Sommaire de l'article",
      updated: "Mis à jour"
    },
    de: {
      author: "Autor",
      breadcrumb: "Breadcrumb",
      breaking: "Eilmeldung",
      contact: "Kontakt",
      correction: "Korrekturen",
      correctionBody: "Wenn ein Fehler bestätigt wird, prüfen und korrigieren wir den Artikel zügig.",
      defaultReadingTime: "Ca. 5 Min. Lesezeit",
      editorialTeam: "Review Guide Redaktion",
      home: "Start",
      keyPoints: "Kernpunkte",
      lastUpdated: "Zuletzt aktualisiert",
      news: "News",
      noNext: "Kein nächster Artikel",
      noPrevious: "Kein vorheriger Artikel",
      noSources: "Bestätigte öffentliche Quellen werden vorbereitet.",
      prevNext: "Vorherige und nächste Artikel",
      published: "Veröffentlicht",
      save: "Speichern",
      sectionLabel: "Abschnitt",
      sourceAndCorrection: "Quellen und Korrekturen",
      sources: "Quellen und Referenzen",
      toc: "Inhaltsverzeichnis",
      updated: "Aktualisiert"
    },
    it: {
      author: "Autore",
      breadcrumb: "Percorso",
      breaking: "Notizia",
      contact: "Contatto",
      correction: "Correzioni",
      correctionBody: "Se viene confermato un errore, controlleremo e correggeremo rapidamente l'articolo.",
      defaultReadingTime: "Circa 5 min di lettura",
      editorialTeam: "Redazione Review Guide",
      home: "Home",
      keyPoints: "Punti chiave",
      lastUpdated: "Ultimo aggiornamento",
      news: "News",
      noNext: "Nessun articolo successivo",
      noPrevious: "Nessun articolo precedente",
      noSources: "Le fonti pubbliche verificate sono in preparazione.",
      prevNext: "Articoli precedente e successivo",
      published: "Pubblicato",
      save: "Salva",
      sectionLabel: "Sezione",
      sourceAndCorrection: "Fonti e correzioni",
      sources: "Fonti e riferimenti",
      toc: "Indice dell'articolo",
      updated: "Aggiornato"
    },
    nl: {
      author: "Auteur",
      breadcrumb: "Kruimelpad",
      breaking: "Update",
      contact: "Contact",
      correction: "Correcties",
      correctionBody: "Als er een fout wordt bevestigd, controleren en corrigeren we het artikel snel.",
      defaultReadingTime: "Ongeveer 5 min lezen",
      editorialTeam: "Review Guide redactie",
      home: "Home",
      keyPoints: "Belangrijkste punten",
      lastUpdated: "Laatst bijgewerkt",
      news: "Nieuws",
      noNext: "Geen volgend artikel",
      noPrevious: "Geen vorig artikel",
      noSources: "Bevestigde openbare bronnen worden voorbereid.",
      prevNext: "Vorige en volgende artikelen",
      published: "Gepubliceerd",
      save: "Opslaan",
      sectionLabel: "Sectie",
      sourceAndCorrection: "Bronnen en correcties",
      sources: "Bronnen en referenties",
      toc: "Inhoud van dit artikel",
      updated: "Bijgewerkt"
    },
    pl: {
      author: "Autor",
      breadcrumb: "Ścieżka",
      breaking: "Pilne",
      contact: "Kontakt",
      correction: "Sprostowania",
      correctionBody: "Jeśli potwierdzimy błąd, szybko sprawdzimy i poprawimy artykuł.",
      defaultReadingTime: "Około 5 min czytania",
      editorialTeam: "Redakcja Review Guide",
      home: "Start",
      keyPoints: "Najważniejsze punkty",
      lastUpdated: "Ostatnia aktualizacja",
      news: "Wiadomości",
      noNext: "Brak następnego artykułu",
      noPrevious: "Brak poprzedniego artykułu",
      noSources: "Potwierdzone źródła publiczne są w przygotowaniu.",
      prevNext: "Poprzednie i następne artykuły",
      published: "Opublikowano",
      save: "Zapisz",
      sectionLabel: "Sekcja",
      sourceAndCorrection: "Źródła i sprostowania",
      sources: "Źródła i odniesienia",
      toc: "Spis treści artykułu",
      updated: "Zaktualizowano"
    },
    tr: {
      author: "Yazar",
      breadcrumb: "Konum",
      breaking: "Son dakika",
      contact: "İletişim",
      correction: "Düzeltmeler",
      correctionBody: "Bir hata doğrulanırsa makaleyi hızlıca inceler ve düzeltiriz.",
      defaultReadingTime: "Yaklaşık 5 dk okuma",
      editorialTeam: "Review Guide editör ekibi",
      home: "Ana sayfa",
      keyPoints: "Öne çıkan noktalar",
      lastUpdated: "Son güncelleme",
      news: "Haberler",
      noNext: "Sonraki makale yok",
      noPrevious: "Önceki makale yok",
      noSources: "Doğrulanmış açık kaynaklar hazırlanıyor.",
      prevNext: "Önceki ve sonraki makaleler",
      published: "Yayınlandı",
      save: "Kaydet",
      sectionLabel: "Bölüm",
      sourceAndCorrection: "Kaynaklar ve düzeltmeler",
      sources: "Kaynaklar ve referanslar",
      toc: "Makale içeriği",
      updated: "Güncellendi"
    },
    id: {
      author: "Penulis",
      breadcrumb: "Navigasi",
      breaking: "Kabar terbaru",
      contact: "Kontak",
      correction: "Koreksi",
      correctionBody: "Jika ada kesalahan yang terkonfirmasi, kami akan meninjau dan memperbaikinya dengan cepat.",
      defaultReadingTime: "Sekitar 5 menit baca",
      editorialTeam: "Tim editorial Review Guide",
      home: "Beranda",
      keyPoints: "Poin utama",
      lastUpdated: "Terakhir diperbarui",
      news: "Berita",
      noNext: "Tidak ada artikel berikutnya",
      noPrevious: "Tidak ada artikel sebelumnya",
      noSources: "Sumber publik terverifikasi sedang disiapkan.",
      prevNext: "Artikel sebelum dan sesudah",
      published: "Terbit",
      save: "Simpan",
      sectionLabel: "Bagian",
      sourceAndCorrection: "Sumber dan koreksi",
      sources: "Sumber dan referensi",
      toc: "Daftar isi artikel",
      updated: "Diperbarui"
    },
    ja: {
      author: "著者",
      breadcrumb: "パンくず",
      breaking: "速報",
      contact: "お問い合わせ",
      correction: "訂正について",
      correctionBody: "この記事の内容に誤りがあった場合は、確認後すみやかに訂正します。",
      defaultReadingTime: "約5分で読了",
      editorialTeam: "レビューガイド編集部",
      home: "ホーム",
      keyPoints: "この記事の要点",
      lastUpdated: "最終更新",
      news: "ニュース",
      noNext: "次の記事はありません",
      noPrevious: "前の記事はありません",
      noSources: "確認した公開ソースは準備中です。",
      prevNext: "前後の記事",
      published: "公開",
      save: "保存",
      sectionLabel: "セクション",
      sourceAndCorrection: "出典と訂正",
      sources: "出典・参考",
      toc: "この記事の目次",
      updated: "更新あり"
    },
    ko: {
      author: "작성자",
      breadcrumb: "현재 위치",
      breaking: "속보",
      contact: "문의하기",
      correction: "정정 안내",
      correctionBody: "내용 오류가 확인되면 검토 후 빠르게 정정합니다.",
      defaultReadingTime: "약 5분",
      editorialTeam: "리뷰 가이드 편집팀",
      home: "홈",
      keyPoints: "이 글의 요점",
      lastUpdated: "최종 업데이트",
      news: "뉴스",
      noNext: "다음 기사가 없습니다",
      noPrevious: "이전 기사가 없습니다",
      noSources: "확인한 공개 출처를 준비 중입니다.",
      prevNext: "이전/다음 기사",
      published: "공개",
      save: "저장",
      sectionLabel: "섹션",
      sourceAndCorrection: "출처와 정정",
      sources: "출처·참고",
      toc: "이 글의 목차",
      updated: "업데이트 있음"
    }
  };
  return labels[language] ?? labels.en;
}

function portugueseNewsLabels(editorialTeam: string, contact: string, prevNext: string): NewsDetailLabels {
  return {
    author: "Autor",
    breadcrumb: "Caminho",
    breaking: "Alerta",
    contact,
    correction: "Correções",
    correctionBody: "Se houver erro neste artigo, vamos rever e corrigir rapidamente.",
    defaultReadingTime: "Cerca de 5 min de leitura",
    editorialTeam,
    home: "Início",
    keyPoints: "Pontos principais",
    lastUpdated: "Última atualização",
    news: "Notícias",
    noNext: "Não há próximo artigo",
    noPrevious: "Não há artigo anterior",
    noSources: "As fontes públicas confirmadas estão em preparação.",
    prevNext,
    published: "Publicado",
    save: "Guardar",
    sectionLabel: "Secção",
    sourceAndCorrection: "Fontes e correções",
    sources: "Fontes e referências",
    toc: "Índice do artigo",
    updated: "Atualizado"
  };
}
