from __future__ import annotations

INFORMATIONAL_EXPLAINER = "informational_explainer"
REVIEW_COMPARISON = "review_comparison"
TRANSLATE_ALL_PRODUCT_MARKETS = "translate_all_product_markets"
SOURCE_MARKET_ONLY = "source_market_only"

COMMERCIAL_INTENTS = {"commercial", "commercial_research", "transactional", "buyer_intent", "comparison"}
COMMERCIAL_ARTICLE_TYPES = {
    "buyer_intent_test_post",
    "comparison_test_post",
    "review",
    "comparison",
    "deal",
    "product_roundup",
}
INFORMATIONAL_ARTICLE_TYPES = {"article", "guide", "official", "news", "explainer"}

BUYER_TERMS = (
    "review",
    "reviews",
    "compare",
    "comparison",
    "price",
    "deal",
    "discount",
    "coupon",
    "buy",
    "buying",
    "try",
    "pricing",
    "subscription",
    "plan",
    "credit",
    "credits",
    "workflow",
    "best",
    "spec",
    "warranty",
    "seller",
    "retailer",
    "promotion",
    "promo",
    "promocao",
    "promoção",
    "comprar",
    "preço",
    "preco",
    "oferta",
    "descuento",
    "precio",
    "할인",
    "가격",
    "비교",
    "추천",
    "구매",
    "리뷰",
    "제품",
    "価格",
    "比較",
    "おすすめ",
    "購入",
    "レビュー",
)

PRODUCT_TERMS = (
    "oled",
    "tv",
    "iphone",
    "smartphone",
    "charger",
    "adapter",
    "power bank",
    "smartwatch",
    "gadget",
    "usb",
    "gan",
    "supplement",
    "magnesium",
    "probiotic",
    "vitamin",
    "collagen",
    "beauty ingredient",
    "samsung",
    "runway",
    "aleph",
    "video editor",
    "video editing",
    "edit studio",
    "mcp",
    "ai tool",
    "creative ai",
    "adobe",
    "premiere",
    "capcut",
    "gaming monitor",
    "monitor",
    "display",
    "qhd",
    "oled",
    "충전기",
    "보조배터리",
    "스마트워치",
    "게이밍",
    "게임",
    "모니터",
    "디스플레이",
    "키보드",
    "마우스",
    "헤드셋",
    "영양제",
    "유산균",
    "비타민",
    "마그네슘",
    "가전",
    "サプリ",
    "充電器",
    "スマホ",
    "ガジェット",
)

INFORMATIONAL_TERMS = (
    "policy",
    "tax",
    "visa",
    "government",
    "deadline",
    "application",
    "official",
    "notice",
    "filing",
    "admission",
    "admissions",
    "school",
    "law",
    "legal",
    "support program",
    "renta",
    "aeat",
    "hacienda",
    "declaración",
    "declaracion",
    "avisos",
    "대입",
    "세금",
    "신고",
    "비자",
    "정부지원",
    "정책",
    "신청",
    "기준",
    "입시",
    "법률",
    "公式",
    "政策",
    "税",
    "申請",
    "入試",
    "暴力",
)

RUMOR_OR_FUTURE_TERMS = ("rumor", "rumors", "leak", "release date", "噂", "未確認", "루머", "출시")

HEALTH_GUARD_TERMS = (
    "supplement",
    "magnesium",
    "probiotic",
    "vitamin",
    "collagen",
    "gut health",
    "sleep",
    "영양제",
    "유산균",
    "비타민",
    "마그네슘",
    "장건강",
    "수면",
    "サプリ",
    "睡眠",
)

PRODUCT_LOCALIZATION_REQUIRED_SIGNALS = [
    "localized title/h1/meta",
    "local search intent and SERP angle",
    "local price, availability, warranty, retailer, and return-policy context",
    "local product candidate availability or explicit no-offer note",
    "non-boilerplate localized examples",
]
