import type { GeneratedProductSpec } from "./generated-product-fixture-types";

export const generatedChargerProductSpecs: GeneratedProductSpec[] = [
  {
    id: "prod-toocki-67w",
    canonicalName: "Toocki-style 67W GaN Charger",
    slug: "toocki-67w-gan-charger",
    category: "usb-c-chargers",
    brandClaim: "Toocki",
    claimType: "max_output",
    claimValue: "67W",
    verifiedTestType: "sustained_output",
    verifiedResult: "61",
    verifiedUnit: "W for 20 minutes",
    optionName: "67W US plug, no cable",
    trapOptionName: "33W cheapest option",
    wattageClaim: 67,
    trapWattageClaim: 33,
    plugType: "US",
    sourceSlug: "toocki-67w",
    price: 18.4,
    shipping: 2.1,
    sellerName: "Toocki Official Store",
    riskTopic: "headline wattage depends on selected 67W SKU"
  },
  {
    id: "prod-rocoren-140w",
    canonicalName: "Rocoren-style 140W GaN Charger",
    slug: "rocoren-140w-gan-charger",
    category: "usb-c-chargers",
    brandClaim: "Rocoren",
    claimType: "max_output",
    claimValue: "140W",
    verifiedTestType: "sustained_output",
    verifiedResult: "118",
    verifiedUnit: "W peak before thermal step-down",
    optionName: "140W US plug, no cable",
    trapOptionName: "100W EU plug option",
    wattageClaim: 140,
    trapWattageClaim: 100,
    plugType: "US",
    sourceSlug: "rocoren-140w",
    price: 42.6,
    shipping: 3.8,
    sellerName: "Rocoren Direct Store",
    riskTopic: "high output claim needs cable and thermal checks"
  },
  {
    id: "prod-kuulaa-30w",
    canonicalName: "Kuulaa-style 30W Mini Charger",
    slug: "kuulaa-30w-mini-charger",
    category: "usb-c-chargers",
    brandClaim: "Kuulaa",
    claimType: "max_output",
    claimValue: "30W",
    verifiedTestType: "sustained_output",
    verifiedResult: "27",
    verifiedUnit: "W for 20 minutes",
    optionName: "30W EU plug",
    trapOptionName: "20W compact option",
    wattageClaim: 30,
    trapWattageClaim: 20,
    plugType: "EU",
    sourceSlug: "kuulaa-30w",
    price: 8.7,
    shipping: 1.4,
    sellerName: "Kuulaa Charger Store",
    riskTopic: "small charger may not match laptop charging intent"
  }
];
