import type { GeneratedProductSpec } from "./generated-product-fixture-types";

export const generatedChargerProductSpecs: GeneratedProductSpec[] = [
  {
    id: "prod-toocki-67w",
    canonicalName: "Toocki-style 67W GaN Charger",
    slug: "toocki-67w-gan-charger",
    category: "usb-c-chargers",
    brandClaim: "Toocki",
    claimType: "max_output",
    claimValue: "67W",
    verifiedTestType: "sustained_output",
    verifiedResult: "61",
    verifiedUnit: "W for 20 minutes",
    optionName: "67W US plug, no cable",
    trapOptionName: "33W cheapest option",
    wattageClaim: 67,
    trapWattageClaim: 33,
    plugType: "US",
    sourceSlug: "toocki-67w",
    price: 18.4,
    shipping: 2.1,
    sellerName: "Toocki Official Store",
    riskTopic: "headline wattage depends on selected 67W SKU"
  },
  {
    id: "prod-rocoren-140w",
    canonicalName: "Rocoren-style 140W GaN Charger",
    slug: "rocoren-140w-gan-charger",
    category: "usb-c-chargers",
    brandClaim: "Rocoren",
    claimType: "max_output",
    claimValue: "140W",
    verifiedTestType: "sustained_output",
    verifiedResult: "118",
    verifiedUnit: "W peak before thermal step-down",
    optionName: "140W US plug, no cable",
    trapOptionName: "100W EU plug option",
    wattageClaim: 140,
    trapWattageClaim: 100,
    plugType: "US",
    sourceSlug: "rocoren-140w",
    price: 42.6,
    shipping: 3.8,
    sellerName: "Rocoren Direct Store",
    riskTopic: "high output claim needs cable and thermal checks"
  },
  {
    id: "prod-kuulaa-30w",
    canonicalName: "Kuulaa-style 30W Mini Charger",
    slug: "kuulaa-30w-mini-charger",
    category: "usb-c-chargers",
    brandClaim: "Kuulaa",
    claimType: "max_output",
    claimValue: "30W",
    verifiedTestType: "sustained_output",
    verifiedResult: "27",
    verifiedUnit: "W for 20 minutes",
    optionName: "30W EU plug",
    trapOptionName: "20W compact option",
    wattageClaim: 30,
    trapWattageClaim: 20,
    plugType: "EU",
    sourceSlug: "kuulaa-30w",
    price: 8.7,
    shipping: 1.4,
    sellerName: "Kuulaa Charger Store",
    riskTopic: "small charger may not match laptop charging intent"
  },
  {
    id: "prod-anker-45w-foldable",
    canonicalName: "Anker-style 45W Foldable Travel Charger",
    slug: "anker-45w-foldable-travel-charger",
    category: "usb-c-chargers",
    brandClaim: "Anker",
    claimType: "max_output",
    claimValue: "45W",
    verifiedTestType: "sustained_output",
    verifiedResult: "41",
    verifiedUnit: "W for 20 minutes",
    optionName: "45W foldable US plug",
    trapOptionName: "25W compact option",
    wattageClaim: 45,
    trapWattageClaim: 25,
    plugType: "US",
    sourceSlug: "anker-45w-foldable",
    price: 21.2,
    shipping: 2.4,
    sellerName: "Anker Travel Store",
    riskTopic: "folding plug listing can mix 25W and 45W options"
  },
  {
    id: "prod-mcdodo-100w-travel-adapter",
    canonicalName: "Mcdodo-style 100W Travel Adapter Charger",
    slug: "mcdodo-100w-travel-adapter-charger",
    category: "travel-adapter-chargers",
    brandClaim: "Mcdodo",
    claimType: "max_output",
    claimValue: "100W",
    verifiedTestType: "sustained_output",
    verifiedResult: "92",
    verifiedUnit: "W peak before step-down",
    optionName: "100W adapter with US/EU plug kit",
    trapOptionName: "65W adapter-only option",
    wattageClaim: 100,
    trapWattageClaim: 65,
    plugType: "US",
    sourceSlug: "mcdodo-100w-travel-adapter",
    price: 34.9,
    shipping: 3.2,
    sellerName: "Mcdodo Adapter Store",
    riskTopic: "travel adapter bundle must match the tested 100W SKU"
  }
];
